name: Deploy to Hetzner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export PATH="/root/.bun/bin:$PATH"
            cd /root/models.kaarel.dev
            git pull
            bun install
            bun run build
            pm2 reload models.kaarel.dev
