name: Deploy to Hetzner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export PATH="/root/.bun/bin:$PATH"
            cd /root/models.kaarel.dev
            git fetch && git reset --hard origin/main
            bun install
            bun run build
            if pm2 describe models.kaarel.dev > /dev/null 2>&1; then
              pm2 reload models.kaarel.dev
            else
              pm2 start pm2.config.cjs
            fi
